### ISSUE TITLE
UTF-8 formatting

### ISSUE THREAD

**Issue by Th3Shadowbroker** [ModdyLP/AncientDonations#1]
In der Klasse ["Language.java"](https://github.com/ModdyLP/AncientDonations/blob/master/src/de/moddylp/AncientDonations/Language.java), scheint die Formatierung der Original-Klasse irgendwie abhanden gekommen zu sein. Somit wird statt § nun � verwendet.

**Comment by ModdyLP** [comment]
Das gucke ich mir mal an.

**Comment by ModdyLP** [comment]
Ist im nächsten Commit
